upgraded the version of a root module to the latest
sourcefuse/terraform-aws-refarch-opensearch pull request #7
Opened 2023-07-18 12:49 UTC by mayank0202

we need to specify these configurations which is defined in the example folder like what should be the instance count , ebs-storage -size , instance-type etc and if we are deploying with 2 AZs then it can be considered as test/dev mode but if its a production level then min 3 azs should be defined and 3 instance count should be there and Ofcourse if 3 azs are there then 3 subnets should be there

https://github.com/cloudposse/terraform-aws-elasticsearch/blob/0.35.1/examples/complete/variables.tf

Can have a look on above link 

Creation time of opensearch is 20-25 minutes and it can take long depending on the configuration
Deletion time is 15 minutes

2023-07-21 14:56 UTC, jamescrowley321 approved these changes

2023-07-21 15:44 UTC, jamescrowley321 commented on example/main.tf
> +      "${var.namespace}-${var.environment}-private-subnet-private${var.region}a",
@tsaucier-sf Which version is correct?

2023-07-21 15:51 UTC, tsaucier-sf requested changes

2023-07-21 15:51 UTC, tsaucier-sf commented on example/main.tf
> +      "${var.namespace}-${var.environment}-private-subnet-private${var.region}a",
@mayank0202 please confirm the naming convention in arc/poc account, but I believe it is now: `${var.namespace}-${var.environment}-private-subnet-private-${var.region}a",`

2023-07-21 15:51 UTC, tsaucier-sf commented on example/main.tf
> +      "${var.namespace}-${var.environment}-private-subnet-private${var.region}b"
@mayank0202 please confirm the naming convention in arc/poc account, but I believe it is now: `${var.namespace}-${var.environment}-private-subnet-private-${var.region}a",`

2023-07-21 15:53 UTC, mayank0202 commented on example/main.tf
> +      "${var.namespace}-${var.environment}-private-subnet-private${var.region}b"
@jamescrowley321  @tsaucier-sf  as i mentioned that i tested this on poc account so this naming convention is in poc account thats why i needed to changed this

2023-07-21 16:01 UTC, jamescrowley321 commented on example/main.tf
> +      "${var.namespace}-${var.environment}-private-subnet-private${var.region}b"
We need to take a look then because that account should have the updated naming conventions, which were there previously.

2023-07-24 13:05 UTC, tsaucier-sf requested changes

2023-07-24 13:05 UTC, tsaucier-sf commented on example/main.tf
> +      "${var.namespace}-${var.environment}-private-subnet-private${var.region}b"
You are missing a hyphen here: `private${var.region}b`
It worked in poc because it's named correctly in `variables.tf`. 
Please fix this typo.

2023-07-24 13:05 UTC, tsaucier-sf commented on example/main.tf
> +      "${var.namespace}-${var.environment}-private-subnet-private${var.region}a",
See below comment

2023-07-25 12:03 UTC, tsaucier-sf approved these changes

2023-07-25 12:03 UTC, merged